//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInfrastructure.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id_contact { get; set; }
        public Nullable<int> id_contact_type { get; set; }
        public string contact1 { get; set; }
        public string contact_name { get; set; }
    
        public virtual contact_type contact_type { get; set; }
    }
}
