//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInfrastructure.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu_item()
        {
            this.page_title = new HashSet<page_title>();
        }
    
        public int id_menu_item { get; set; }
        public string menu_item_text { get; set; }
        public string menu_item_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<page_title> page_title { get; set; }
    }
}
