//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInfrastructure.DataBaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class websitedatabase : DbContext
    {
        public websitedatabase()
            : base("name=websitedatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<contact_type> contact_type { get; set; }
        public virtual DbSet<menu_item> menu_item { get; set; }
        public virtual DbSet<page_sub_title> page_sub_title { get; set; }
        public virtual DbSet<page_title> page_title { get; set; }
    }
}
