//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInfrastructure.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_sub_title
    {
        public int id_page_subtitle { get; set; }
        public Nullable<int> id_page_title { get; set; }
        public string subtitle { get; set; }
        public string subtitle_description { get; set; }
        public string button_link_text { get; set; }
        public string linkUrl { get; set; }
    
        public virtual page_title page_title { get; set; }
    }
}
